import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mesita Unyu
 */
public class FrameSuhu extends javax.swing.JFrame {

    /**
     * Creates new form FrameSuhu
     */
    public FrameSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFrom = new javax.swing.ButtonGroup();
        buttonGroupTo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCelcius1 = new javax.swing.JRadioButton();
        btnFahrenheit1 = new javax.swing.JRadioButton();
        btnCalvin1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btnCelcius2 = new javax.swing.JRadioButton();
        btnFahrenheit2 = new javax.swing.JRadioButton();
        btnCalvin2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtOutput = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Input");

        jLabel2.setText("From");

        buttonGroupFrom.add(btnCelcius1);
        btnCelcius1.setText("Celcius");
        btnCelcius1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelcius1ActionPerformed(evt);
            }
        });

        buttonGroupFrom.add(btnFahrenheit1);
        btnFahrenheit1.setText("Fahrenheit");

        buttonGroupFrom.add(btnCalvin1);
        btnCalvin1.setText("Calvin");

        jLabel3.setText("To");

        buttonGroupTo.add(btnCelcius2);
        btnCelcius2.setText("Celcius");

        buttonGroupTo.add(btnFahrenheit2);
        btnFahrenheit2.setText("Fahrenheit");

        buttonGroupTo.add(btnCalvin2);
        btnCalvin2.setText("Calvin");

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Result");

        btnClose.setText("keluar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(54, 54, 54)
                                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(49, 49, 49)
                                    .addComponent(txtOutput))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnFahrenheit1)
                                                .addComponent(btnCalvin1)
                                                .addComponent(btnCelcius1))))
                                    .addGap(83, 83, 83)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnFahrenheit2)
                                                .addComponent(btnCelcius2)
                                                .addComponent(btnCalvin2))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButton1)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClose))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCelcius1)
                    .addComponent(btnCelcius2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFahrenheit1)
                    .addComponent(btnFahrenheit2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalvin1)
                    .addComponent(btnCalvin2))
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnClose))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double input;
        float rumus;
        String result;
        
        input=Double.valueOf(txtInput.getText());
            if(btnCelcius1.isSelected()){
                if(btnCelcius2.isSelected()){
                    rumus = (float) input;
                    result =String.valueOf(rumus);
                    txtOutput.setText(result);
                }
                if(btnFahrenheit2.isSelected()){
                    rumus = (float)((input*9/5)+32);
                    result = String.valueOf(rumus);
                    txtOutput.setText(result);
                }
                if(btnCalvin2.isSelected()){
                    rumus = (float) (input + 273.15);
                    result = String.valueOf(rumus);
                    txtOutput.setText(result);
                }
                
            }
            else if(btnFahrenheit1.isSelected()){
                if(btnFahrenheit2.isSelected()){
                    rumus = (float) input;
                    result = String.valueOf(rumus);
                    txtOutput.setText(result);  
                }
                if(btnCelcius2.isSelected()){
                    rumus = (float) ((input-32)/1.8);
                    result = String.valueOf(rumus);
                    txtOutput.setText(result);
                }
                if(btnCalvin2.isSelected()){
                    rumus = (float) ((input+459.67)/1.8);
                    result = String.valueOf(rumus);
                    txtOutput.setText(result);
                }
            }
            else if(btnCalvin1.isSelected()){
                if(btnCalvin2.isSelected()){
                    rumus = (float) input;
                    result = String.valueOf(rumus);
                    txtOutput.setText(result);
                }
                if(btnFahrenheit2.isSelected()){
                    rumus = (float) ((input-273.15)*9/5+32);
                    result = String.valueOf(rumus);
                    txtOutput.setText(result);
                }
                if(btnCelcius2.isSelected()){
                    rumus = (float) (input-273.15);
                    result = String.valueOf(rumus);
                    txtOutput.setText(result);
                }
                
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCelcius1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelcius1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCelcius1ActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        int pesan = JOptionPane.showConfirmDialog(null, "Program Keluar", "Yakin Akan Keluar Program",JOptionPane.YES_NO_OPTION);
        if(pesan==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnCalvin1;
    private javax.swing.JRadioButton btnCalvin2;
    private javax.swing.JRadioButton btnCelcius1;
    private javax.swing.JRadioButton btnCelcius2;
    private javax.swing.JButton btnClose;
    private javax.swing.JRadioButton btnFahrenheit1;
    private javax.swing.JRadioButton btnFahrenheit2;
    private javax.swing.ButtonGroup buttonGroupFrom;
    private javax.swing.ButtonGroup buttonGroupTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtOutput;
    // End of variables declaration//GEN-END:variables
}
